apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: liveness-exec
spec:
  containers:
    - name: liveness
      image: busybox
      # Run custom command, creating a file '/tmp/healthy' and then enter an infinite loop to prevent completion
      command:
        [
          "/bin/sh",
          "-ec",
          "touch /tmp/healthy; while :; do echo '.'; sleep 5; done",
        ]
      livenessProbe:
        # Define a custom command as liveness probe (can also be e.g. http-request)
        exec:
          command:
            # Will succeed when the file /tmp/healthy exists
            - cat
            - /tmp/healthy
        initialDelaySeconds: 5
        periodSeconds: 5
